server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  mapper-locations: classpath*:kr/co/ch/boridaengdaeng/**/maps/*xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
