server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

file: dir=D:/Developer/ch/src/main/webapp/WEB-INF/upload/

mybatis:
  mapper-locations: classpath*:kr/co/ch/bori/**/maps/*xml

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    hikari:
      boridaengdaeng:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/boridaengdaeng?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: boridaengdaeng
        password: 'qhflWkd8872!'
